spring.application.name=gymcore
spring.profiles.active=local
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

workload.service.url=http://trainer-workload-service

resilience4j.circuitbreaker.instances.workloadService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.workloadService.sliding-window-size=5
resilience4j.circuitbreaker.instances.workloadService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.workloadService.wait-duration-in-open-state=10s

spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=${spring.application.name}

logging.pattern.level=%5p [%X{transactionId:-}]
